// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rfs.proto

package rfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileEntry_FileType int32

const (
	FileEntry_DIR  FileEntry_FileType = 0
	FileEntry_FILE FileEntry_FileType = 1
)

// Enum value maps for FileEntry_FileType.
var (
	FileEntry_FileType_name = map[int32]string{
		0: "DIR",
		1: "FILE",
	}
	FileEntry_FileType_value = map[string]int32{
		"DIR":  0,
		"FILE": 1,
	}
)

func (x FileEntry_FileType) Enum() *FileEntry_FileType {
	p := new(FileEntry_FileType)
	*p = x
	return p
}

func (x FileEntry_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileEntry_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_rfs_proto_enumTypes[0].Descriptor()
}

func (FileEntry_FileType) Type() protoreflect.EnumType {
	return &file_rfs_proto_enumTypes[0]
}

func (x FileEntry_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileEntry_FileType.Descriptor instead.
func (FileEntry_FileType) EnumDescriptor() ([]byte, []int) {
	return file_rfs_proto_rawDescGZIP(), []int{0, 0}
}

type FileEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File  string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Size  uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Group string `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	//Optional fields for file.
	BlockReplication uint32        `protobuf:"varint,5,opt,name=block_replication,json=blockReplication,proto3" json:"block_replication,omitempty"`
	BlockSize        uint32        `protobuf:"varint,6,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Locations        *LocatedBlock `protobuf:"bytes,7,opt,name=locations,proto3" json:"locations,omitempty"`
	FileId           uint64        `protobuf:"varint,8,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Content          []byte        `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Flags            uint32        `protobuf:"varint,10,opt,name=flags,proto3" json:"flags,omitempty"`
	Namespace        string        `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_rfs_proto_rawDescGZIP(), []int{0}
}

func (x *FileEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FileEntry) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FileEntry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileEntry) GetBlockReplication() uint32 {
	if x != nil {
		return x.BlockReplication
	}
	return 0
}

func (x *FileEntry) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *FileEntry) GetLocations() *LocatedBlock {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *FileEntry) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileEntry) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FileEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type LocatedBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block     *Block              `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Offset    uint64              `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Locations []*VolumeServerInfo `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	VolumeId  []int32             `protobuf:"varint,4,rep,packed,name=volumeId,proto3" json:"volumeId,omitempty"`
}

func (x *LocatedBlock) Reset() {
	*x = LocatedBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocatedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocatedBlock) ProtoMessage() {}

func (x *LocatedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_rfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocatedBlock.ProtoReflect.Descriptor instead.
func (*LocatedBlock) Descriptor() ([]byte, []int) {
	return file_rfs_proto_rawDescGZIP(), []int{1}
}

func (x *LocatedBlock) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *LocatedBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LocatedBlock) GetLocations() []*VolumeServerInfo {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *LocatedBlock) GetVolumeId() []int32 {
	if x != nil {
		return x.VolumeId
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId uint64 `protobuf:"varint,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Size    uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_rfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_rfs_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *Block) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VolumeServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	VolumeId uint32 `protobuf:"varint,3,opt,name=volumeId,proto3" json:"volumeId,omitempty"`
}

func (x *VolumeServerInfo) Reset() {
	*x = VolumeServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeServerInfo) ProtoMessage() {}

func (x *VolumeServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeServerInfo.ProtoReflect.Descriptor instead.
func (*VolumeServerInfo) Descriptor() ([]byte, []int) {
	return file_rfs_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeServerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VolumeServerInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VolumeServerInfo) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

var File_rfs_proto protoreflect.FileDescriptor

var file_rfs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x66, 0x73,
	0x22, 0xe1, 0x02, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x2b, 0x0a, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2f,
	0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x66, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x01, 0x22, 0x99, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x66, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x33, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x66, 0x73, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64,
	0x22, 0x35, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x66,
	0x65, 0x76, 0x65, 0x72, 0x79, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x72, 0x66, 0x73, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x66,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rfs_proto_rawDescOnce sync.Once
	file_rfs_proto_rawDescData = file_rfs_proto_rawDesc
)

func file_rfs_proto_rawDescGZIP() []byte {
	file_rfs_proto_rawDescOnce.Do(func() {
		file_rfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_rfs_proto_rawDescData)
	})
	return file_rfs_proto_rawDescData
}

var file_rfs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rfs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rfs_proto_goTypes = []interface{}{
	(FileEntry_FileType)(0),  // 0: rfs.FileEntry.FileType
	(*FileEntry)(nil),        // 1: rfs.FileEntry
	(*LocatedBlock)(nil),     // 2: rfs.LocatedBlock
	(*Block)(nil),            // 3: rfs.Block
	(*VolumeServerInfo)(nil), // 4: rfs.VolumeServerInfo
}
var file_rfs_proto_depIdxs = []int32{
	2, // 0: rfs.FileEntry.locations:type_name -> rfs.LocatedBlock
	3, // 1: rfs.LocatedBlock.block:type_name -> rfs.Block
	4, // 2: rfs.LocatedBlock.locations:type_name -> rfs.VolumeServerInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rfs_proto_init() }
func file_rfs_proto_init() {
	if File_rfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocatedBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rfs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rfs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rfs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rfs_proto_goTypes,
		DependencyIndexes: file_rfs_proto_depIdxs,
		EnumInfos:         file_rfs_proto_enumTypes,
		MessageInfos:      file_rfs_proto_msgTypes,
	}.Build()
	File_rfs_proto = out.File
	file_rfs_proto_rawDesc = nil
	file_rfs_proto_goTypes = nil
	file_rfs_proto_depIdxs = nil
}
